// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPheMB1VN1PCwN53Yw3VkMZP3ex8k6Ok8',
    appId: '1:270508360814:web:cfacb33331197fea89927f',
    messagingSenderId: '270508360814',
    projectId: 'edulearn-9f182',
    authDomain: 'edulearn-9f182.firebaseapp.com',
    storageBucket: 'edulearn-9f182.firebasestorage.app',
    measurementId: 'G-QLGKHBRGT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk7gdPVl_m7aQ5WZQuQF6wl1ck7T9qbAg',
    appId: '1:270508360814:android:cc44e79260e38fad89927f',
    messagingSenderId: '270508360814',
    projectId: 'edulearn-9f182',
    storageBucket: 'edulearn-9f182.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOwiVMcRHygaFEQlPlRNtpO_hxb2gB_S0',
    appId: '1:270508360814:ios:8a66db9311b400b289927f',
    messagingSenderId: '270508360814',
    projectId: 'edulearn-9f182',
    storageBucket: 'edulearn-9f182.firebasestorage.app',
    iosBundleId: 'com.example.edulearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOwiVMcRHygaFEQlPlRNtpO_hxb2gB_S0',
    appId: '1:270508360814:ios:8a66db9311b400b289927f',
    messagingSenderId: '270508360814',
    projectId: 'edulearn-9f182',
    storageBucket: 'edulearn-9f182.firebasestorage.app',
    iosBundleId: 'com.example.edulearn',
  );
}
